version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgis/postgis:14-master
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /data/postgres
    volumes:
       - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
       - postgres:/data/postgres
    ports:
      - "5438:5432"
    restart: unless-stopped
  
volumes:
    postgres:
  